aktosch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include('collection_agency.urls', namespace='collection_agency')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

collection_agency/urls.py
from django.urls import path
from . import views
from . import api

app_name = 'collection_agency'
urlpatterns = [
    path("", views.load_file, name="load_file"),
    path("accounts/", api.DebtListView.as_view(), name='debt-list'),
    path("ws-load-file", api.wsUploadFile.as_view(), name="wsUploadFile")
]

collection_agency/models.py
from django.db import models
from .choices import DebtStatus


class CollectionAgency(models.Model):
    name = models.CharField(max_length=100)


# Files uploaded by a collection agency
class CollectionFiles(models.Model):
    file = models.FileField(verbose_name="Files", upload_to="CollectionFiles/%Y/%m/%d", null=False, blank=False)
    collection_agency = models.ForeignKey(CollectionAgency, on_delete=models.CASCADE, related_name='agency')


# Clients that hires a collection agency and also has consumers
class Client(models.Model):
    reference = models.CharField(max_length=50, unique=True)
    collection_agency = models.ForeignKey(CollectionAgency, on_delete=models.CASCADE, related_name='hiredAgency')


# Consumers that own the debt
class Consumer(models.Model):
    name = models.CharField(max_length=70)
    address = models.CharField(max_length=100, unique=True)
    ssn = models.CharField(max_length=30, unique=True)


class Debt(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='client')
    consumer = models.ForeignKey(Consumer, on_delete=models.CASCADE, related_name='consumer')
    status = models.CharField(
        max_length=30,
        choices=DebtStatus.choices,
        default=DebtStatus.INACTIVE
    )
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=True, null=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['client', 'consumer'], name='unique_debt_client_consumer')
        ]

collection_agency/views.py
from django.shortcuts import render

# Create your views here.
def load_file(request):
    return render(request, "collection_agency/base.html")

collection_agency/templates/collection_agency/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>WELCOME [COLLECTION_AGENCY]</h1>
<form id="formNewFile" onsubmit="loadFile();" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label for="inputFile">Load file</label>
        <input class="form-control" id="inputFile" name="inputFile" type="file" placeholder="Load CSV File" data-validations="file"/>
        <div class="invalid-feedback">Please provide a CSV File</div>
        <button class="btn btn-primary fw-500" type="submit" id="submitBtn" data-validations="none">Load CSV</button>
    </div>
</form>
<script src="https://dsotodevsa.blob.core.windows.net/aktos/collection_agency/js/tools/getCookie.js"></script>
<script src="https://dsotodevsa.blob.core.windows.net/aktos/collection_agency/js/tools/fetchRequest.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://dsotodevsa.blob.core.windows.net/aktos/collection_agency/js/tools/swalUtils.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="https://dsotodevsa.blob.core.windows.net/aktos/collection_agency/js/loadFile.js"></script>
<script>
    let wsUploadFile = "{% url 'collection_agency:wsUploadFile' %}";
</script>
</body>
</html>